## set to null for any param that's not required for your search
## search parameters
token: ""                                          #[string][default: ""][REQUIRED] <API Token could be acquired from your dashboard>
search_terms: null                                 #[string][default: ""]  e.g. "abc.net.au"
AND_terms: null                                    #[string][default: ""]  e.g. "abc.net.au"
NOT_terms: null                                    #[string][default: ""]  e.g. "abc.net.au"
start_date : null                                  #[string][default: null] e.g."2020-02-02"
end_date: null                                     #[string][default: datetime.NOW] e.g."2020-02-02"
lists: null                                        #[string][default:null] e.g. "123,456"
output_filename: null                              #[string][default: <datetime.NOW>.csv] e.g. "output.csv"
offset: 0                                          #[int][default: 0] 
log: true                                          #[boolean][default: false]

im -metadata "2020-02_image_urls_by_day.csv" -fieldname "media_url" -s 50 -d
im -metadata "2020-02_image_urls_by_day.csv" -fieldname "media_url" -s 50
im -img fb -s 50
im -metadata jane.txy.json -img downloads\user\jane.txy
im -metadata jane.txy.json -img downloads\user\jane.txy -zip downloads.zip